# Generated by Django 4.2.7 on 2026-01-25 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0002_trainer_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program Assignment',
                'verbose_name_plural': 'Program Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='client',
        ),
        migrations.RemoveField(
            model_name='session',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='program',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClientTrainerAssignment',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='programassignment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='programs.program'),
        ),
        migrations.AlterUniqueTogether(
            name='programassignment',
            unique_together={('program', 'member')},
        ),
    ]
