# Generated by Django 4.2.7 on 2026-01-29 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0003_programassignment_remove_session_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('in-person', 'In-Person'), ('virtual', 'Virtual')], default='in-person', max_length=20)),
                ('attendance_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('present', 'Present'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
