# Generated by Django 4.2.7 on 2026-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
