# Generated by Django 4.2.7 on 2026-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
